seed: 42

data_module:
  data_path: ariel-data-challenge-2025
  batch_size: 32
  num_workers: 4
  test_size: 0.1
  full_train: False
  fold: 4

fabric:
  devices: auto
  accelerator: cuda
  strategy: auto
  precision: 32

model:
  airs_output_features: 128
  fgs_output_features: 32
  meta_output_features: 32

optimizer:
  lr: 0.001
  weight_decay: 0.01
  betas: [0.9, 0.999]
  # momentum: 0.9

scheduler:
  pct_cosine: 0.95

train:
  max_epochs: 1000