seed: 42

data_module:
  data_path: ariel-data-challenge-2025
  batch_size: 1
  num_workers: 8
  test_size: 0.1

fabric:
  devices: auto
  accelerator: cuda
  strategy: auto
  precision: 32

model:
  num_layers: 3
  hidden_channels: 8

optimizer:
  lr: 0.0001
  weight_decay: 0.0
  betas: [0.9, 0.999]
  # momentum: 0.5

scheduler:
  pct_cosine: 0.95

train:
  max_epochs: 500