seed: 42

data_module:
  data_path: ariel-data-challenge-2025
  batch_size: 32
  num_workers: 8
  test_size: 0.1

fabric:
  devices: auto
  accelerator: cuda
  strategy: auto
  precision: 64

model:
  num_layers: 4 
  hidden_channels: 8
  airs_project_coef: 64
  fgs_output_features: 32
  meta_output_features: 32

optimizer:
  lr: 0.001
  weight_decay: 0.0
  betas: [0.9, 0.999]
  # momentum: 0.9

scheduler:
  pct_cosine: 0.95

train:
  max_epochs: 50