seed: 42
gauss_loss: False

data_module:
  data_path: ariel-data-challenge-2025
  batch_size: 32
  num_workers: 0
  test_size: 0.1
  full_train: False
  fold: 0

fabric:
  devices: auto
  accelerator: cuda
  strategy: auto
  precision: 16-mixed

model:
  checkpoint: null

optimizer:
  lr: 0.0001
  weight_decay: 0.01
  betas: [0.9, 0.999]
  # momentum: 0.9

scheduler:
  pct_cosine: 0.95

train:
  max_epochs: 500